### ISSUE TITLE
When setting a MetadataCollection's pagination path to a subdirectory the template doesn't point to the right location

### ISSUE THREAD

**Issue by hswolff** [yarnjs/yarn#4]
when `_config.yml` has:

```yaml
collections:
  tag:
    metadata: tags
    pagination:
      template: tag
      size: 6
      permalink_index: /blog/tag/:metadata/
      permalink_page:  /blog/tag/:metadata/:page/
```

The generated template code that links to the tag index page does not include the `/blog/` in its path.
